name: Generate Snake
on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: ihsansaif313
          svg_out_path: dist/github-contribution-grid-snake.svg
          color_snake: "#44F748"  # Match your theme
          color_dots: "#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9"

      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
